### ISSUE TITLE
Link to WebAPI docs

### ISSUE THREAD

**Issue by redhead** [atp-team/Gustav#2]
It would be really nice if you provided a link to docs for WebAPI for Česká spořitelna. It was a bit hard to find it on Google for me.

**Comment by jmachan-zz** [comment]
Thx 4 feedback. I created a pullrequest with information about documenation on our WebAPI portal.

**Comment by Vratislav** [comment]
For anyone looking for it right now, here are the docs to WebAPI: https://developers.csas.cz

**Comment by krtek** [comment]
Fixed with 557c36c33b0301141a0b2ca64a743f89ead99619.
