### ISSUE TITLE
Takže nové rozhraní?

### ISSUE THREAD

**Issue by Jirka7** [atp-team/Gustav#4]
Mám konkrétní dotaz a to na aplikaci která by fungovala s Českou Spořitelnou. Zajímá mne jestli Česká Spořitelna nabízí možnost zjištění účtu klienta na který si přejete zaslat peněžní částku. Pokud ano můžete mi sdělit cestu která by k tomu vedla? Budu vám zavázán.

**Comment by krtek** [comment]
Dobrý den,

nejsem zaměstnanec ČS, takže mě berte s rezervou. Pokud vím, tak nic takového API Spořitelny nenabízí. 

Dokumentaci k nabízeným API najdete na [developerském portálu ČS](https://www.ersteapihub.com).
