### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Jirka7** [atp-team/Gustav#5]
Well my question is about Ceska Sporitelna and their new web portal ersteapihub.com. Ive been searching how to make it work with my plans and make a company and actualy find costumers to deal with. My question about this portal is how can find account number of costumer which might contact me about financial servicess. Would you help me with my question Jiri.

**Comment by krtek** [comment]
Hello there,

AFAIK there is no way how to find an account number for a customer unless he/she gives your application access through authorization.
In that case you can use standard [Accounts API](https://www.ersteapihub.com/docs/apis/bank.csas/v3%2Fnetbanking).
